name: Trigger auto deployment for bloyal-ca-24804196

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feature ]
    paths:
    - '**'
    - '.github/workflows/bloyal-ca-24804196-AutoDeployTrigger-454c2f61-f267-4352-871e-141efbb57a76.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: bloyalpocreg24804196.azurecr.io
          username: ${{ secrets.BLOYALCA24804196_REGISTRY_USERNAME }}
          password: ${{ secrets.BLOYALCA24804196_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bloyalpocreg24804196.azurecr.io/bloyal-ca-24804196:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BLOYALCA24804196_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n bloyal-ca-24804196 -g rg-bloyal --server bloyalpocreg24804196.azurecr.io --username  ${{ secrets.BLOYALCA24804196_REGISTRY_USERNAME }} --password ${{ secrets.BLOYALCA24804196_REGISTRY_PASSWORD }}
            az containerapp update -n bloyal-ca-24804196 -g rg-bloyal --image bloyalpocreg24804196.azurecr.io/bloyal-ca-24804196:${{ github.sha }}
